### ISSUE TITLE
Modify sort

### ISSUE THREAD

**Issue by fsobral** [fsobral/pack-u#1]
`sort` has to consider the ID of items besides their area.

**Comment by evcastelani** [comment]
Now, the Sort function works with Id priority. But the implementation is very slow...I need to check if the solution was correct considering the new sort algorithm. Whe we set iId=0 is ok.

**Comment by fsobral** [comment]
I think the error is to consider `nContainers` in this subroutine. Just sort items according to their id AND size. Then, let the future subroutine of issue #2 deals with which container should be used for each item. I'll work on #2 now.
