### ISSUE TITLE
Create a functional site to show Pack-U working "online"

### ISSUE THREAD

**Issue by fsobral** [fsobral/pack-u#12]

**Comment by evcastelani** [comment]
Something like this https://evcastelani.github.io/Liga.jl/? 

Remark: Considering the idea, not the explanation (isn't good enough in this moment)

**Comment by fsobral** [comment]
No. I think the title was not very good. My idea is a complete working example, where you can select some items and see the delivery cost being computed "online". Is an example to guide the IT team to implement/use Pack-U. I've edited it.

(Nice site, by the way!)

**Comment by evcastelani** [comment]
I got it! But in this case we have to host on a server. Are you planning to use an Amazon Server?

**Comment by fsobral** [comment]
No. We run a local server when it is necessary to show it. Is a "complete example" in the sense that anybody can set up the server and try. Of course, a true server would be great, but expensive.

**Comment by evcastelani** [comment]
Ok,  my mistake...
