### ISSUE TITLE
About the site

### ISSUE THREAD

**Issue by evcastelani** [fsobral/pack-u#13]
I have two observations.

1. The command
 ``sudo aptitude install python3 couchdb pip3``
doesn't work for install pip3. Aptitude work well to install python3 couchdb but not pip3. The same thing happens with apt-get. The best way that I found was using 
``sudo easy_install3 pip``

2. When we are testing all the time the message in the site is Calculating ... but the result was expressed in bash. For example, in my test the output in bash was 

> emerson@emerson-H81M-H:~/Documentos/packu_site_test/pack-u/build$

> python3 site.py
http://0.0.0.0:8080/ 
INFO: Created item  4.00  4.00   0
INFO: Created item  5.70  5.70   0
INFO: Created item  5.70  5.70   0
INFO: Created item  7.50  7.50   0
127.0.0.1:35990 - - [15/Jan/2018 09:44:22] "HTTP/1.1 GET /" - 200 OK
127.0.0.1:35990 - - [15/Jan/2018 09:44:22] "HTTP/1.1 GET /favicon.ico" - 404 Not Found
INFO: Created item  4.00  4.00   0
INFO: Created item  5.70  5.70   0
INFO: Created item  5.70  5.70   0
INFO: Created item  7.50  7.50   0
INFO: Created container 40.00 30.00   0
INFO: Created container 28.50 17.50   0
DEBUG: Key 20,10,10,10 not found in cache.
DEBUG:    70 items of type   1 fit in container   1
DEBUG:    35 items of type   2 fit in container   1
DEBUG:    35 items of type   3 fit in container   1
DEBUG:    20 items of type   4 fit in container   1
INFO: Packed 0 items of type 1 in 0 containers of type 1
INFO: Packed 0 items of type 2 in 0 containers of type 1
INFO: Packed 0 items of type 3 in 0 containers of type 1
INFO: Packed 0 items of type 4 in 0 containers of type 1
DEBUG: Solution not found in cache. Will run Pack-U.
Note: The following floating-point exceptions are signalling: IEEE_DENORMAL
INFO: Added key 20,10,10,10
DEBUG: New solution saved to cache. Key: 20,10,10,10
127.0.0.1:36020 - - [15/Jan/2018 09:44:30] "HTTP/1.1 GET /calc" - 200 OK
^Cemerson@emerson-H81M-H:~/Documentos/packu_site_test/pack-u/build$ 

Is it a correct behavior?

**Comment by fsobral** [comment]
1. Thanks, `easyinstall` also works, but has to be related to Python 3. The correct command is

          sudo aptitude install python3-pip

  1. No. It should answer the 'price', after calculating. Set up the server again and try the command

          http://localhost:8080/calc?data=20,10,10,10

      The browser should answer

          The delivery cost will be: R$ 44.40. (Took 1.30s)

I have made a small change, please try again with the address `http://127.0.0.1:8080/`

**Comment by evcastelani** [comment]
This command 

> sudo aptitude install python3-pip

works well if we setup main server in linux but not in Brazil server. But ok, it isn't a problem.

I believe that I am having some render problem...
Packu is running and find the solution but looks that frete isn't render. I don't know why? I have both python version in my computer 2.7 and 3.5. When a type

> pip3 --version

results

> pip 9.0.1 from /usr/local/lib/python3.5/dist-packages/pip-9.0.1-py3.5.egg (python 3.5)

So pip3 looks ok!

Futhermore, in my computer, when a type

>python3 

runs python 3.5

and 

>python

runs python 2.7. Could it be the problem?

**Comment by evcastelani** [comment]
I am sorry, just for complement....when I try the command

> http://localhost:8080/calc?data=20,10,10,10

the correct price is showed.

but not by calculated button.

**Comment by fsobral** [comment]
Good. I think the problem is the [Same Origin Policy](https://en.wikipedia.org/wiki/Same-origin_policy) which blocks some Javascript calls, for security reasons. Try on Firefox, please. I've tried on Firefox and Chrome. Moreover, try to start the server with the command

    python3 site.py '127.0.0.1:8080'

**Comment by evcastelani** [comment]
I am not sure if this is the problem. I tried in Chrome, Firefox, Opera and tried with a Electron app window...In all cases, the same problem, ie, the solution was obtained but without show the correct frete page...Yours security options in Firefox are default?

**Comment by fsobral** [comment]
Hum... I think so. Lets make other tests.

  1. Using Firefox, open the web site, then right click and open the Inspector. Then, go to the Network tab, reload the page and try an example. It should appear a GET call there, and you can inspect this call to see what was the message (in the right, 'Response' sub-tab). It shouldn't be empty...

      ![scr1](https://user-images.githubusercontent.com/5919115/34955678-7acafdac-fa1d-11e7-93e5-ad264295f1a9.png)

  1. Put some values for a test. Using the inspector, open the Console tab, then call the function `calculateIt()` directly, to see if some error occur. In my case, there is no message, but the cost is calculated and updated.

**Comment by evcastelani** [comment]
I believe that you right about Same Origin Policy...see this print screen
![screenshot at 2018-01-15 16 10 52](https://user-images.githubusercontent.com/13542537/34956115-dc184376-fa0e-11e7-9ec3-23f2d80afc2e.png)
![screenshot at 2018-01-15 16 10 37](https://user-images.githubusercontent.com/13542537/34956116-dc3610d6-fa0e-11e7-8a0b-0094c852a9f9.png)

**Comment by fsobral** [comment]
Ah! Have you gotten the latest version? I think I've just fixed this
problem.

**Comment by evcastelani** [comment]
You right! I'm really sorry!!!!!! I was thinking that it was update in my folder. I don't know why I was thinking that!!! Sorry again! The good news in this case: everything is working!
