### ISSUE TITLE
Some observations

### ISSUE THREAD

**Issue by evcastelani** [fsobral/pack-u#9]
It is not a bug but in example t13, the solution found is different of the right solution. I believe that the reason for the divergence is the heuristic phase where items are allocated respecting the width or height of the first item allocated in a certain range.

**Comment by fsobral** [comment]
This example `t13` was very good. Now the code was improved with a new heuristic, which gives the expected solution. I've also created `t14` for testing it.

**Comment by evcastelani** [comment]
Awesome! I'll see the new example and try create new ones.
